services:
  sixpackapi:
    build: .
    command: "sixpack"
    environment:
      - SIXPACK_CONFIG_ENABLED=true
      - SIXPACK_CONFIG_REDIS_PORT=6379
      - SIXPACK_CONFIG_REDIS_HOST=redis
      - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
    ports:
      - "5000:5000"

  sixpackweb:
    build: .
    command: "sixpack-web"
    environment:
      - SIXPACK_CONFIG_ENABLED=true
      - SIXPACK_CONFIG_REDIS_PORT=6379
      - SIXPACK_CONFIG_REDIS_HOST=redis
      - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
    ports:
      - "5001:5001"

  redis:
    image: redis:4.0.14
